### ISSUE TITLE
Submit to CRAN or bioconductor?

### ISSUE THREAD

**Issue by jfy133** [jfy133/cuperdec#5]
http://r-pkgs.had.co.nz/release.html

**Comment by jfy133** [comment]
Recommendation from @nevrome: "And use the windows test system - it always catches something you missed in your local checks"

**Comment by nevrome** [comment]
Ja - https://win-builder.r-project.org/

```
devtools::check_win_release()
devtools::check_win_devel()
```

**Comment by jfy133** [comment]
Done!
